# Generated by Django 3.2.5 on 2021-07-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slu',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
