# Generated by Django 3.2.5 on 2021-07-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20210723_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slu',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='slu',
            new_name='slug',
        ),
    ]
