# Generated by Django 3.2.5 on 2021-08-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleforms', '0003_actor_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='experience',
            field=models.PositiveIntegerField(max_length=255),
        ),
    ]
