# Generated by Django 3.2.5 on 2021-08-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleforms', '0004_alter_director_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='experience',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
